# Generated by Django 4.2.7 on 2023-11-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_content_remove_textcontent_step_and_more'),
        ('users', '0008_alter_user_managers_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(null=True, related_name='users', to='courses.course'),
        ),
    ]
