# Generated by Django 4.2.7 on 2023-12-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_content_remove_textcontent_step_and_more'),
        ('users', '0010_alter_user_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='users', to='courses.course'),
        ),
    ]
