# Generated by Django 4.2.7 on 2024-01-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_content_remove_textcontent_step_and_more'),
        ('users', '0011_alter_user_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses_favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_for_user', to='courses.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='courses_owned',
            field=models.ManyToManyField(blank=True, related_name='created_by_user', to='courses.course'),
        ),
    ]
