# Generated by Django 4.2.7 on 2024-01-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_content_remove_textcontent_step_and_more'),
        ('users', '0012_user_courses_favorite_user_courses_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses_in_progress',
            field=models.ManyToManyField(blank=True, related_name='in_progress_for_user', to='courses.course'),
        ),
    ]
