# Generated by Django 4.2.7 on 2023-11-21 04:30

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(upload_to=courses.models.course_preview_upload_path),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_num',
            field=models.IntegerField(),
        ),
    ]
