# Generated by Django 4.2.7 on 2023-11-24 17:21

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_preview_alter_lesson_lesson_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_num', models.IntegerField()),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=courses.models.content_upload_path)),
                ('width', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.step')),
            ],
            options={
                'unique_together': {('step', 'content_num')},
            },
        ),
        migrations.RemoveField(
            model_name='textcontent',
            name='step',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='step',
        ),
        migrations.DeleteModel(
            name='ImageContent',
        ),
        migrations.DeleteModel(
            name='TextContent',
        ),
        migrations.DeleteModel(
            name='VideoContent',
        ),
    ]
